### ISSUE TITLE
README bridgedb-1.1.0.zip inconsistent with jars (and jars names outdated anyway)

### ISSUE THREAD

**Issue by egonw** [amarillion/BridgeDb#14]
The README writes:

bridgedb.jar - always needed. 
    This includes file, rdb, biomart and BridgeRest drivers.

But the driver is in a separate jar:

$ jar tvf org.bridgedb.jar | grep IDMapperRdb
$ jar tvf org.bridgedb.rdb.jar | grep IDMapperRdb
   218 Thu Feb 24 18:37:06 CET 2011 org/bridgedb/rdb/IDMapperRdb$1.class
  2887 Thu Feb 24 18:37:06 CET 2011 org/bridgedb/rdb/IDMapperRdb$DriverClient.class
  1170 Thu Feb 24 18:37:06 CET 2011 org/bridgedb/rdb/IDMapperRdb$DriverJdbc.class
  1201 Thu Feb 24 18:37:06 CET 2011 org/bridgedb/rdb/IDMapperRdb$DriverPgdb.class
  1788 Thu Feb 24 18:37:06 CET 2011 org/bridgedb/rdb/IDMapperRdb.class

**Comment by egonw** [comment]
Oh, never mind... already fixed in this commit:

http://svn.bigcat.unimaas.nl/bridgedb/trunk@564

**Comment by amarillion** [comment]
Hi Egon,

Could it be that you're looking at an old README? I updated it a few 
weeks ago.

## 

Martijn

**Comment by amarillion** [comment]
Never mind, if you're looking at the README packaged in 
bridgedb-1.1.0.zip, it's definitely outdated. But this is fixed in trunk.

## 

Martijn

**Comment by egonw** [comment]
Yes, see my comment minutes after the bug report...
